name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Run dotnet format
        run: |
          dotnet format style src/AtomFeed/AtomFeed.csproj --verbosity normal --verify-no-changes
          dotnet format analyzers src/AtomFeed/AtomFeed.csproj --verbosity normal --verify-no-changes
          dotnet format style tests/AtomFeed.Tests/AtomFeed.Tests.csproj --verbosity normal --verify-no-changes
          dotnet format analyzers tests/AtomFeed.Tests/AtomFeed.Tests.csproj --verbosity normal --verify-no-changes

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-restore --verbosity normal
